### PR TITLE
fix(path): "/" repeat

### LINKED ISSUE #98: Too many "/" in URL path
**What is the issue about**:
```
var childrenDesc = definition.Descriptor{
	Path:        "/api/v1/",
	Definitions: []definition.Definition{},
	Consumes:    []string{"application/json"},
	Produces:    []string{"application/json"},
	Children: []definition.Descriptor{
		{
			Path: "",
			Children: []definition.Descriptor{
				{
					Path: "/",
					Children: []definition.Descriptor{
						{
							Path: "/ping",
							Definitions: []definition.Definition{
								{
									Method:   definition.Get,
									Function: echoHandle,
									Results: []definition.Result{
										{Destination: definition.Data},
										{Destination: definition.Error},
									},
								},
							},
						},
					},
				},
			},
		},
	},
}
```

**What happened**:
parser `/api/v1//ping`

**What you expected to happen**:
`/api/v1/ping`

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by yejiayu**
**What this PR does**
fix #98 

**why we need it**

**Special notes for your reviewer**:

### CODE REVIEW

File: service/builder_test.go [hunk 1]
```diff
@@ -153,6 +154,72 @@ func TestServer(t *testing.T) {
...
+			},
+		},
+	},
+}
+
+func echoHandle(ctx context.Context) (string, error) {
+	return "pong", nil
+}
+
+func TestChilderPath(t *testing.T) {
```
Comment (kdada) [inline service/builder_test.go]: What's the `Childer`

File: service/builder_test.go [hunk 2]
```diff
@@ -153,6 +154,72 @@ func TestServer(t *testing.T) {
...
+		t.Fatal(err)
+	}
+	s, err := builder.Build()
+	if err != nil {
+		t.Fatal(err)
+	}
+	req = req.WithContext(context.Background())
+	resp := newRW()
+	s.ServeHTTP(resp, req)
+	if resp.code != 200 {
```
Comment (kdada) [inline service/builder_test.go]: Check the response body.

File: service/builder_test.go [hunk 3]
```diff
@@ -135,6 +135,7 @@ func TestServer(t *testing.T) {
 	}
 	req = req.WithContext(context.Background())
 	req.Body = ioutil.NopCloser(bytes.NewBuffer(data))
+
```
Comment (kdada) [inline service/builder_test.go]: Delete the newline.

File: service/builder.go [hunk 4]
```diff
@@ -89,7 +89,13 @@ func (b *builder) AddDescriptor(descriptors ...definition.Descriptor) error {
 }
 
 func (b *builder) addDescriptor(prefix string, consumes []string, produces []string, descriptor definition.Descriptor) {
-	path := strings.Join([]string{prefix, strings.Trim(descriptor.Path, "/")}, "/")
+	var path string
+	if descriptor.Path != "" && descriptor.Path != "/" {
```
Comment (kdada) [inline service/builder.go]: It's wrong. What if `descriptor.Path == "//"`?

File: service/builder.go [hunk 5]
```diff
@@ -89,7 +89,16 @@ func (b *builder) AddDescriptor(descriptors ...definition.Descriptor) error {
 }
 
 func (b *builder) addDescriptor(prefix string, consumes []string, produces []string, descriptor definition.Descriptor) {
-	path := strings.Join([]string{prefix, strings.Trim(descriptor.Path, "/")}, "/")
+	var path string
+
+	trimPath := strings.Trim(descriptor.Path, "/")
+	// if root path or "///test"
```
Comment (kdada) [inline service/builder.go]: Let your comments is more like a sentence.

File: service/builder.go [hunk 6]
```diff
@@ -89,7 +89,16 @@ func (b *builder) AddDescriptor(descriptors ...definition.Descriptor) error {
...
+	if prefix == "" || trimPath != "" {
+		path = strings.Join([]string{prefix, trimPath}, "/")
```
Comment (kdada) [inline service/builder.go]: What if `prefix == ""` and `trimPath == ""`? It still creates an useless `/`.

File: service/builder.go [hunk 7]
```diff
@@ -89,8 +89,21 @@ func (b *builder) AddDescriptor(descriptors ...definition.Descriptor) error {
...
+
+	if trimPath != "" {
+		path = strings.Join([]string{prefix, trimPath}, "/")
+	} else {
+		path = prefix
+	}
+
+	path = "/" + strings.Trim(path, "/")
+
+	if path != "" && trimPath == "" {
```
Comment (kdada) [inline service/builder.go]: `path != ""` is always tenable.

File: service/builder.go [hunk 8]
```diff
@@ -89,7 +89,15 @@ func (b *builder) AddDescriptor(descriptors ...definition.Descriptor) error {
...
 
 func (b *builder) addDescriptor(prefix string, consumes []string, produces []string, descriptor definition.Descriptor) {
-	path := strings.Join([]string{prefix, strings.Trim(descriptor.Path, "/")}, "/")
+	trimPath := strings.Trim(descriptor.Path, "/")
+	path := strings.Join([]string{prefix, trimPath}, "/")
+
+	// If the pre path is not the root path and the current path is an empty string.
+	if prefix != "" && trimPath == "" && len(descriptor.Definitions) > 0 {
+		b.logger.Warningf("%s descriptor.Path not a root path and is no specific path."+
+			"If you don't enable RedirectTrailingSlash filter, Definitions will not be executed", descriptor.Description)
```
Comment (kdada) [inline service/builder.go]: The description is wrong. I'll fix it and move it to apposite place in next pr.
